=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DomainClient::DomainPublicAdapterWebApiModelsV1PropertiesClaimData
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DomainPublicAdapterWebApiModelsV1PropertiesClaimData' do
  before do
    # run before each test
    @instance = DomainClient::DomainPublicAdapterWebApiModelsV1PropertiesClaimData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainPublicAdapterWebApiModelsV1PropertiesClaimData' do
    it 'should create an instance of DomainPublicAdapterWebApiModelsV1PropertiesClaimData' do
      expect(@instance).to be_instance_of(DomainClient::DomainPublicAdapterWebApiModelsV1PropertiesClaimData)
    end
  end
  describe 'test attribute "claimant"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Owner", "Tenant", "Investor"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.claimant = value }.not_to raise_error
      # end
    end
  end

end
