=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DomainClient::DomainListingAdminServiceV1ModelCommercialPrice
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DomainListingAdminServiceV1ModelCommercialPrice' do
  before do
    # run before each test
    @instance = DomainClient::DomainListingAdminServiceV1ModelCommercialPrice.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainListingAdminServiceV1ModelCommercialPrice' do
    it 'should create an instance of DomainListingAdminServiceV1ModelCommercialPrice' do
      expect(@instance).to be_instance_of(DomainClient::DomainListingAdminServiceV1ModelCommercialPrice)
    end
  end
  describe 'test attribute "price_unit_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["totalAmount", "perSqm"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.price_unit_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "price_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["gross", "net"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.price_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "gst_option_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["na", "inc", "ex"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.gst_option_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "price_reduction"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "display_text"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
