=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DomainClient::DomainDemographicsServiceV1ModelDemographicsModel
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DomainDemographicsServiceV1ModelDemographicsModel' do
  before do
    # run before each test
    @instance = DomainClient::DomainDemographicsServiceV1ModelDemographicsModel.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainDemographicsServiceV1ModelDemographicsModel' do
    it 'should create an instance of DomainDemographicsServiceV1ModelDemographicsModel' do
      expect(@instance).to be_instance_of(DomainClient::DomainDemographicsServiceV1ModelDemographicsModel)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "total"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "year"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "items"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
