=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DomainClient::DomainSearchServiceV2ModelSystemNullableDomainSearchWebApiV2ModelsSortBy
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DomainSearchServiceV2ModelSystemNullableDomainSearchWebApiV2ModelsSortBy' do
  before do
    # run before each test
    @instance = DomainClient::DomainSearchServiceV2ModelSystemNullableDomainSearchWebApiV2ModelsSortBy.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainSearchServiceV2ModelSystemNullableDomainSearchWebApiV2ModelsSortBy' do
    it 'should create an instance of DomainSearchServiceV2ModelSystemNullableDomainSearchWebApiV2ModelsSortBy' do
      expect(@instance).to be_instance_of(DomainClient::DomainSearchServiceV2ModelSystemNullableDomainSearchWebApiV2ModelsSortBy)
    end
  end
  describe 'test attribute "sort_key"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Default", "Suburb", "Price", "DateUpdated", "InspectionTime", "Proximity", "SoldDate"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.sort_key = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "direction"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Ascending", "Descending"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.direction = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "proximity_to"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
