=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DomainClient::DomainPublicAdapterWebApiModelsV1EnquiriesEnquiryReport
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DomainPublicAdapterWebApiModelsV1EnquiriesEnquiryReport' do
  before do
    # run before each test
    @instance = DomainClient::DomainPublicAdapterWebApiModelsV1EnquiriesEnquiryReport.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainPublicAdapterWebApiModelsV1EnquiriesEnquiryReport' do
    it 'should create an instance of DomainPublicAdapterWebApiModelsV1EnquiriesEnquiryReport' do
      expect(@instance).to be_instance_of(DomainClient::DomainPublicAdapterWebApiModelsV1EnquiriesEnquiryReport)
    end
  end
  describe 'test attribute "recipients_delivery_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "delivery_method"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["email", "sms"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.delivery_method = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "enquiry_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["listing", "devProject", "newDevLanding", "agencyProfile", "agentProfile", "contractRequest", "vendorEnquiry"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.enquiry_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "reference_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "sender"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "subject"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "meta_data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
