=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'date'

module DomainClient
  # Address structure for property
  class DomainListingAdminServiceV1ModelAddress
    # What granularity to display the properties location at
    attr_accessor :display_option

    # State
    attr_accessor :state

    # Unit number for apartments, maximum 30 characters
    attr_accessor :unit_number

    # Street name, maximum 100 characters
    attr_accessor :street

    # Provide the latitude and longitude for the property to show in the map
    attr_accessor :suggested_geo_location

    # Street number, maximum 20 characters
    attr_accessor :street_number

    # Suburb name , maximum 50 characters
    attr_accessor :suburb

    # Postcode
    attr_accessor :postcode

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'display_option' => :'displayOption',
        :'state' => :'state',
        :'unit_number' => :'unitNumber',
        :'street' => :'street',
        :'suggested_geo_location' => :'suggestedGeoLocation',
        :'street_number' => :'streetNumber',
        :'suburb' => :'suburb',
        :'postcode' => :'postcode'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'display_option' => :'String',
        :'state' => :'String',
        :'unit_number' => :'String',
        :'street' => :'String',
        :'suggested_geo_location' => :'DomainListingAdminServiceV1ModelGeoLocation',
        :'street_number' => :'String',
        :'suburb' => :'String',
        :'postcode' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'displayOption')
        self.display_option = attributes[:'displayOption']
      end

      if attributes.has_key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.has_key?(:'unitNumber')
        self.unit_number = attributes[:'unitNumber']
      end

      if attributes.has_key?(:'street')
        self.street = attributes[:'street']
      end

      if attributes.has_key?(:'suggestedGeoLocation')
        self.suggested_geo_location = attributes[:'suggestedGeoLocation']
      end

      if attributes.has_key?(:'streetNumber')
        self.street_number = attributes[:'streetNumber']
      end

      if attributes.has_key?(:'suburb')
        self.suburb = attributes[:'suburb']
      end

      if attributes.has_key?(:'postcode')
        self.postcode = attributes[:'postcode']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      display_option_validator = EnumAttributeValidator.new('String', ['fullAddress', 'streetAndSuburb', 'suburbOnly', 'regionOnly', 'areaOnly', 'stateOnly', 'unspecified'])
      return false unless display_option_validator.valid?(@display_option)
      state_validator = EnumAttributeValidator.new('String', ['nsw', 'vic', 'act', 'sa', 'wa', 'tas', 'qld', 'nt'])
      return false unless state_validator.valid?(@state)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] display_option Object to be assigned
    def display_option=(display_option)
      validator = EnumAttributeValidator.new('String', ['fullAddress', 'streetAndSuburb', 'suburbOnly', 'regionOnly', 'areaOnly', 'stateOnly', 'unspecified'])
      unless validator.valid?(display_option)
        fail ArgumentError, 'invalid value for "display_option", must be one of #{validator.allowable_values}.'
      end
      @display_option = display_option
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] state Object to be assigned
    def state=(state)
      validator = EnumAttributeValidator.new('String', ['nsw', 'vic', 'act', 'sa', 'wa', 'tas', 'qld', 'nt'])
      unless validator.valid?(state)
        fail ArgumentError, 'invalid value for "state", must be one of #{validator.allowable_values}.'
      end
      @state = state
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          display_option == o.display_option &&
          state == o.state &&
          unit_number == o.unit_number &&
          street == o.street &&
          suggested_geo_location == o.suggested_geo_location &&
          street_number == o.street_number &&
          suburb == o.suburb &&
          postcode == o.postcode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [display_option, state, unit_number, street, suggested_geo_location, street_number, suburb, postcode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DomainClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
