=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'date'

module DomainClient
  # Commercial Property
  class DomainListingAdminServiceV1ModelCommercialProperty
    # Commercial property types ['aquaculture', 'dairyFarming', 'developmentLand', 'fishingForestry', 'hotelLeisure', 'industrialWarehouse', 'irrigationServices', 'livestock', 'internationalCommercial', 'medicalConsulting', 'offices', 'parkingCarSpace', 'retail', 'ruralCommercialFarming', 'showroomsBulkyGoods', 'servicedOffices', 'other', 'cropping', 'viticulture', 'mixedFarming', 'grazing', 'horticulture', 'equine', 'farmlet', 'orchard', 'ruralLifestyle'].
    attr_accessor :property_type

    # Building Type
    attr_accessor :building_type

    # List of image files, photos or floor plans related to the listing
    attr_accessor :images

    # Address Details
    attr_accessor :address

    # Parking Details
    attr_accessor :parking

    # Building area in square metres
    attr_accessor :area

    # Land Area
    attr_accessor :land_area

    # List of PDF files related to the listing
    attr_accessor :pdfs

    # Is the property liveability compliant
    attr_accessor :is_marked_for_liveability

    # Name of the property up to 70 characters
    attr_accessor :property_name

    # Short location information up to 30 character, e.g.: Greenhills Beach
    attr_accessor :location

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'property_type' => :'propertyType',
        :'building_type' => :'buildingType',
        :'images' => :'images',
        :'address' => :'address',
        :'parking' => :'parking',
        :'area' => :'area',
        :'land_area' => :'landArea',
        :'pdfs' => :'pdfs',
        :'is_marked_for_liveability' => :'isMarkedForLiveability',
        :'property_name' => :'propertyName',
        :'location' => :'location'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'property_type' => :'Array<String>',
        :'building_type' => :'String',
        :'images' => :'Array<DomainListingAdminServiceV1ModelPropertyMedia>',
        :'address' => :'DomainListingAdminServiceV1ModelAddress',
        :'parking' => :'DomainListingAdminServiceV1ModelParking',
        :'area' => :'DomainListingAdminServiceV1ModelArea',
        :'land_area' => :'DomainListingAdminServiceV1ModelLandArea',
        :'pdfs' => :'Array<DomainListingAdminServiceV1ModelPropertyPdf>',
        :'is_marked_for_liveability' => :'BOOLEAN',
        :'property_name' => :'String',
        :'location' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'propertyType')
        if (value = attributes[:'propertyType']).is_a?(Array)
          self.property_type = value
        end
      end

      if attributes.has_key?(:'buildingType')
        self.building_type = attributes[:'buildingType']
      end

      if attributes.has_key?(:'images')
        if (value = attributes[:'images']).is_a?(Array)
          self.images = value
        end
      end

      if attributes.has_key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.has_key?(:'parking')
        self.parking = attributes[:'parking']
      end

      if attributes.has_key?(:'area')
        self.area = attributes[:'area']
      end

      if attributes.has_key?(:'landArea')
        self.land_area = attributes[:'landArea']
      end

      if attributes.has_key?(:'pdfs')
        if (value = attributes[:'pdfs']).is_a?(Array)
          self.pdfs = value
        end
      end

      if attributes.has_key?(:'isMarkedForLiveability')
        self.is_marked_for_liveability = attributes[:'isMarkedForLiveability']
      end

      if attributes.has_key?(:'propertyName')
        self.property_name = attributes[:'propertyName']
      end

      if attributes.has_key?(:'location')
        self.location = attributes[:'location']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      building_type_validator = EnumAttributeValidator.new('String', ['whole', 'part', 'na'])
      return false unless building_type_validator.valid?(@building_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] building_type Object to be assigned
    def building_type=(building_type)
      validator = EnumAttributeValidator.new('String', ['whole', 'part', 'na'])
      unless validator.valid?(building_type)
        fail ArgumentError, 'invalid value for "building_type", must be one of #{validator.allowable_values}.'
      end
      @building_type = building_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          property_type == o.property_type &&
          building_type == o.building_type &&
          images == o.images &&
          address == o.address &&
          parking == o.parking &&
          area == o.area &&
          land_area == o.land_area &&
          pdfs == o.pdfs &&
          is_marked_for_liveability == o.is_marked_for_liveability &&
          property_name == o.property_name &&
          location == o.location
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [property_type, building_type, images, address, parking, area, land_area, pdfs, is_marked_for_liveability, property_name, location].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DomainClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
