=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'

# Unit tests for DomainClient::AddressLocatorsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AddressLocatorsApi' do
  before do
    # run before each test
    @instance = DomainClient::AddressLocatorsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddressLocatorsApi' do
    it 'should create an instance of AddressLocatorsApi' do
      expect(@instance).to be_instance_of(DomainClient::AddressLocatorsApi)
    end
  end

  # unit tests for address_locators_get
  # Retrieves matching ids for use in other services.
  # Use this endpoint to retrieve IDs that may be used to query information from other endpoints.    For example use &#x60;id&#x60; of the &#x60;Suburb&#x60; level to query [&#x60;demographics&#x60;](/docs/endpoints/demographics/demographics_get)
  # @param search_level Requested search level. Valid values are: &#x60;Address&#x60;, and &#x60;Suburb&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :unit_number Unit number
  # @option opts [String] :street_number Street number
  # @option opts [String] :street_name Street name
  # @option opts [String] :street_type Street type
  # @option opts [String] :suburb Suburb
  # @option opts [String] :state State
  # @option opts [String] :postcode Postcode
  # @return [Array<DomainAPMServiceV3ModelAPMAPIModelsTokenisedSearchV3AddressDataModel>]
  describe 'address_locators_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
