=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'

# Unit tests for DomainClient::DisclaimersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DisclaimersApi' do
  before do
    # run before each test
    @instance = DomainClient::DisclaimersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DisclaimersApi' do
    it 'should create an instance of DisclaimersApi' do
      expect(@instance).to be_instance_of(DomainClient::DisclaimersApi)
    end
  end

  # unit tests for disclaimers_get
  # Retrieves disclaimers for given ids
  # @param [Hash] opts the optional parameters
  # @option opts [String] :ids Comma separated list of ids. Eg. \&quot;1,2,3\&quot;
  # @return [Array<DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel>]
  describe 'disclaimers_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for disclaimers_get_by_product
  # Retrieves disclaimers for given product
  # @param product Possible product values: &#x60;PropertyData&#x60;, &#x60;AURIN&#x60;, &#x60;HomePriceGuide&#x60;
  # @param [Hash] opts the optional parameters
  # @return [Array<DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel>]
  describe 'disclaimers_get_by_product test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
