=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'

# Unit tests for DomainClient::MeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MeApi' do
  before do
    # run before each test
    @instance = DomainClient::MeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MeApi' do
    it 'should create an instance of MeApi' do
      expect(@instance).to be_instance_of(DomainClient::MeApi)
    end
  end

  # unit tests for me_get_my_agencies
  # Retrieves summary agency information associated to the current user.
  # @param [Hash] opts the optional parameters
  # @return [Array<DomainPublicAdapterWebApiModelsV1AgenciesBriefAgencySummary>]
  describe 'me_get_my_agencies test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
