=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'

# Unit tests for DomainClient::SuburbPerformanceStatisticsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SuburbPerformanceStatisticsApi' do
  before do
    # run before each test
    @instance = DomainClient::SuburbPerformanceStatisticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SuburbPerformanceStatisticsApi' do
    it 'should create an instance of SuburbPerformanceStatisticsApi' do
      expect(@instance).to be_instance_of(DomainClient::SuburbPerformanceStatisticsApi)
    end
  end

  # unit tests for suburb_performance_statistics_get
  # Retrieves suburb performance data
  # @param state State where the suburb is
  # @param suburb_id Suburb Identifier.  Use the &#x60;addressLocators&#x60; resource to determine the suburbId.
  # @param property_category Property Category. Valid values are: &#x60;house&#x60;, &#x60;unit&#x60;, &#x60;land&#x60;
  # @param chronological_span The size of each chunk of information we want in months. 3, 6, or 12.
  # @param t_plus_from Countdown number in chronological spans from the current (current chronological span is 1)
  # @param t_plus_to Countdown number in chronological spans from the current (current chronological span is 1, 2 chronological spans ago is 3)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :bedrooms Restrict statistics to properties with this number of bedrooms
  # @option opts [String] :values Values to be returned for the series.  If the field is not provided, all available values for the SeriesInfo will be returned. You can specify multiple values using comma separated text.  Valid values are: &#x60;MedianSoldPrice&#x60;, &#x60;AuctionNumberAuctioned&#x60;, &#x60;AuctionNumberSold&#x60;, &#x60;AuctionNumberWithdrawn&#x60;, &#x60;NumberSold&#x60;, &#x60;LowestSoldPrice&#x60;, &#x60;HighestSoldPrice&#x60;, &#x60;5thPercentileSoldPrice&#x60;, &#x60;25thPercentileSoldPrice&#x60;, &#x60;75thPercentileSoldPrice&#x60;, &#x60;95thPercentileSoldPrice&#x60;, &#x60;DaysOnMarket&#x60;, &#x60;DiscountPercentage&#x60;, &#x60;MedianRentListingPrice&#x60;, &#x60;NumberRentListing&#x60;, &#x60;HighestRentListingPrice&#x60;, &#x60;LowestRentListingPrice&#x60;, &#x60;MedianSaleListingPrice&#x60;, &#x60;NumberSaleListing&#x60;, &#x60;HighestSaleListingPrice&#x60;, &#x60;LowestSaleListingPrice&#x60;
  # @return [DomainAPMServiceV2ModelAPMAPIModelsSuburbV2SuburbPerformanceModel]
  describe 'suburb_performance_statistics_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
