=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'

# Unit tests for DomainClient::WebhooksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @instance = DomainClient::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@instance).to be_instance_of(DomainClient::WebhooksApi)
    end
  end

  # unit tests for webhooks_create_subscription
  # Creates a subscription
  # @param id Webhook identifier
  # @param subscription Subscription data
  # @param [Hash] opts the optional parameters
  # @return [DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription]
  describe 'webhooks_create_subscription test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_delete_subscription
  # Deletes a webhook subscription
  # @param id Subscription identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'webhooks_delete_subscription test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_get_subscription
  # Retrieves a webhook subscription
  # @param id Subscription identifier
  # @param [Hash] opts the optional parameters
  # @return [DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription]
  describe 'webhooks_get_subscription test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_list_subscriptions
  # Retreives all webhook subscriptions
  # @param id Subscriber (Webhook) ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_number 
  # @option opts [Integer] :page_size 
  # @return [Array<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>]
  describe 'webhooks_list_subscriptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
