=begin
#Domain Group API V1

#Provides public access to Domain's microservices

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'uri'

module DomainClient
  class MeApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Retrieves summary agency information associated to the current user.
    # @param [Hash] opts the optional parameters
    # @return [Array<DomainPublicAdapterWebApiModelsV1AgenciesBriefAgencySummary>]
    def me_get_my_agencies(opts = {})
      data, _status_code, _headers = me_get_my_agencies_with_http_info(opts)
      data
    end

    # Retrieves summary agency information associated to the current user.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<DomainPublicAdapterWebApiModelsV1AgenciesBriefAgencySummary>, Fixnum, Hash)>] Array<DomainPublicAdapterWebApiModelsV1AgenciesBriefAgencySummary> data, response status code and response headers
    def me_get_my_agencies_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MeApi.me_get_my_agencies ...'
      end
      # resource path
      local_var_path = '/v1/me/agencies'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['oauth2']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<DomainPublicAdapterWebApiModelsV1AgenciesBriefAgencySummary>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MeApi#me_get_my_agencies\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
